version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip3 install -r requirements.txt
      - python/save-cache
      - run:
          command: py.test-3
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
